### ISSUE TITLE
unsettled function: expressCreateServer

### ISSUE THREAD

**Issue by jolly-jump** [ether/ep_who_did_what#5]
Hi,

```
[ERROR] console - UNSETTLED FUNCTION BUG IN HOOK FUNCTION (plugin: ep_who_did_what, function name: /opt/etherpad-lite/node_modules/ep_who_did_what/express:expressCreateServer, hook: expressCreateServer): The hook function neither called the callback nor returned a non-undefined value. This is prohibited because it will result in freezes when a future version of Etherpad updates the hook to support asynchronous behavior.
```
is shown by the logs when I try to start ep with ep_who_did_what installed. 
I use docker, etherpadlite main repository and the following plugins:
ETHERPAD_PLUGINS="ep_headings2 ep_comments_page ep_embedded_hyperlinks2 ep_ldapauth ep_author_neat ep_readonly_guest ep_cursortrace ep_copy_paste_images ep_adminpads2 ep_whiteboard ep_who_did_what ep_dis
able_reset_authorship_colours ep_print"

If I try to use the plugin (click on the magnifying glass in the history), then etherpad completely bites the dust saying:

```
2021-01-05 16:26:13.185] [ERROR] console - TypeError: callback is not a function
etherpad-devel        |     at async.setImmediate (/opt/etherpad-lite/node_modules/ep_who_did_what/exportWhoDidWhat.js:97:7)
etherpad-devel        |     at Immediate.defer (/opt/etherpad-lite/src/node_modules/async/dist/async.js:73:45)
etherpad-devel        |     at runCallback (timers.js:705:18)
etherpad-devel        |     at tryOnImmediate (timers.js:676:5)
etherpad-devel        |     at processImmediate (timers.js:658:5)
etherpad-devel        |     at process.topLevelDomainCallback (domain.js:126:23)
```

**Comment by JohnMcLear** [comment]
Will fix ASAP

**Comment by JohnMcLear** [comment]
Fixed in https://github.com/ether/ep_who_did_what/commit/29965f27f5b48dcfa62c1102287d5323767a1981

Will auto release once linting is fine, for now use repo to test.

**Comment by jolly-jump** [comment]
Ok, Thanks as well here: you are too quick for me.
One more question: the ui works. I am just not sure, if the plugin records "added" and "removed" owners correctly.
I installed the plugin now and the page does remember the edits from other users but the plugin does not show these other editing users - it only shows edits by the original author - I am not sure - but it also does so for edits that came from different users.

However, when I *now* edit something, the plugin seems to report the other users correctly.

This might not be a problem at all when the premise is, that ep_who_did_what has to be installed before the pad is created.

**Comment by JohnMcLear** [comment]
Yea I noticed that, I think it's a separate bug if you want to make an issue for that,  Iwill try find time but it might be a few weeks because I have other things on.

**Comment by jolly-jump** [comment]
no, thanks, i'm good, as long as it works "from now on". Cheers!
